// <auto-generated />
using System;
using Meat.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meat.Repositories.Migrations
{
    [DbContext(typeof(MeatContext))]
    [Migration("20260717180933_41_FaenaMasterData")]
    partial class _41_FaenaMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meat.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAlmacen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAlmacenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("TipoAlmacenId");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("Meat.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIngresosBrutos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCliente")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoRenspa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCUIG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("ClienteId", "EstablecimientoId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("ClientesEstablecimientos");
                });

            modelBuilder.Entity("Meat.Domain.Denticiones.Denticion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDenticionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Codigo");

                    b.HasIndex("EspecieId");

                    b.HasIndex("TipoDenticionId");

                    b.ToTable("Denticiones");
                });

            modelBuilder.Entity("Meat.Domain.DestinosComerciales.DestinoComercial", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("DestinosComerciales");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIngresosBrutos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroInscripcionRuca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpresaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoEmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Meat.Domain.Especies.Especie", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoEstablecimiento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRuca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSenasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEstablecimiento")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("Meat.Domain.EstablecimientosEspecies.EstablecimientoEspecie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("EstablecimientoId", "EspecieId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("EstablecimientosEspecies");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoIngresoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmisionDte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroIngreso")
                        .HasColumnType("bigint");

                    b.Property<string>("OrigenHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatenteCamion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteJaula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoNeto")
                        .HasColumnType("float");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<string>("Transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsoHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UsuarioAprobacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEstablecimientoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("EstadoIngresoId");

                    b.HasIndex("OrigenHaciendaId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("UsoHaciendaId");

                    b.HasIndex("EstablecimientoId", "NumeroIngreso")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("IngresosHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaPesada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPesada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PesoIngreso")
                        .HasColumnType("float");

                    b.Property<string>("TipoEspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("TipoEspecieId");

                    b.ToTable("IngresosHaciendasPesadas");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaUbicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PesoPromedio")
                        .HasColumnType("float");

                    b.Property<string>("TipoEspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TropaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("EstadoHaciendaId");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("TipoEspecieId");

                    b.HasIndex("TropaId");

                    b.ToTable("IngresosHaciendasUbicaciones");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoListaMatanzaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<long>("NumeroLista")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioConfirmacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("EstadoListaMatanzaId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("EstablecimientoId", "NumeroLista")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("EstablecimientoId", "Fecha", "EspecieId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL AND [EstadoListaMatanzaId] <> 'ANULADA'");

                    b.ToTable("ListasMatanzas");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanzaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlmacenDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFaenada")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListaMatanzaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<string>("TipoEspecieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TropaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenDestinoId");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ListaMatanzaId");

                    b.HasIndex("TipoEspecieId");

                    b.HasIndex("TropaId");

                    b.ToTable("ListasMatanzasDetalles");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanzaMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlmacenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CantidadAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadNueva")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListaMatanzaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecuenciaAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("SecuenciaNueva")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TropaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaMatanzaId");

                    b.ToTable("ListasMatanzasMovimientos");
                });

            modelBuilder.Entity("Meat.Domain.Materiales.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoTeorico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMaterialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnidadMedidaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaterialId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Meat.Domain.MotivosDecomisos.MotivoDecomiso", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EspecieId");

                    b.ToTable("MotivosDecomisos");
                });

            modelBuilder.Entity("Meat.Domain.Numeradores.Numerador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecieCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoNumerador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("EstablecimientoId", "EspecieCodigo", "Codigo")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("Numeradores");
                });

            modelBuilder.Entity("Meat.Domain.NumeradoresTropas.NumeradorTropa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<long>("UltimoNumeroTropa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("ClienteEstablecimientoId", "EspecieCodigo")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("NumeradoresTropas");
                });

            modelBuilder.Entity("Meat.Domain.OrigenesHaciendas.OrigenHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("OrigenesHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.Parametros.Parametro", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Meat.Domain.Provincias.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Meat.Domain.Puestos.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erp_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPuestoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("TipoPuestoId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("Meat.Domain.Roles.Rol", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoSucursal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Erp_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Meat.Domain.Tipificaciones.Tipificacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinoComercialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<double>("PesoDesde")
                        .HasColumnType("float");

                    b.Property<double>("PesoHasta")
                        .HasColumnType("float");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("TipificacionOficialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoEspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UnidadFaenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnidadMedidaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Codigo");

                    b.HasIndex("DestinoComercialId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("TipificacionOficialId");

                    b.HasIndex("TipoEspecieId");

                    b.HasIndex("UnidadFaenaId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Tipificaciones");
                });

            modelBuilder.Entity("Meat.Domain.TipificacionesOficiales.TipificacionOficial", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EspecieId");

                    b.ToTable("TipificacionesOficiales");
                });

            modelBuilder.Entity("Meat.Domain.TiposAlmacenes.TipoAlmacen", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Familia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposAlmacenes");
                });

            modelBuilder.Entity("Meat.Domain.TiposClientes.TipoCliente", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposClientes");
                });

            modelBuilder.Entity("Meat.Domain.TiposContusiones.TipoContusion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EspecieId");

                    b.ToTable("TiposContusiones");
                });

            modelBuilder.Entity("Meat.Domain.TiposDenticiones.TipoDenticion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EspecieId");

                    b.ToTable("TiposDenticiones");
                });

            modelBuilder.Entity("Meat.Domain.TiposEmpresas.TipoEmpresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEmpresas");
                });

            modelBuilder.Entity("Meat.Domain.TiposEspecies.TipoEspecie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoTeorico")
                        .HasColumnType("float");

                    b.Property<string>("TipoSexoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("TipoSexoId");

                    b.ToTable("TiposEspecies");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosHacienda.TipoEstadoHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosHacienda");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosIngresos.TipoEstadoIngreso", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosIngresos");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosListasMatanzas.TipoEstadoListaMatanza", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosListasMatanzas");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosTropas.TipoEstadoTropa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosTropas");
                });

            modelBuilder.Entity("Meat.Domain.TiposMateriales.TipoMaterial", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMateriales");
                });

            modelBuilder.Entity("Meat.Domain.TiposMediciones.TipoMedicion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMediciones");
                });

            modelBuilder.Entity("Meat.Domain.TiposPuestos.TipoPuesto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposPuestos");
                });

            modelBuilder.Entity("Meat.Domain.TiposSexos.TipoSexo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposSexos");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.Tropa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoTropaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NumeroTropa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("EstadoTropaId");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("ClienteEstablecimientoId", "EspecieCodigo", "NumeroTropa")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("Tropas");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.TropaMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoResultanteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TropaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoResultanteId");

                    b.HasIndex("TropaId", "Secuencia")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("TropasMovimientos");
                });

            modelBuilder.Entity("Meat.Domain.UnidadesFaenas.UnidadFaena", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadCuartos")
                        .HasColumnType("int");

                    b.Property<string>("CodigoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid?>("UnidadComplementariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadComplementariaId");

                    b.HasIndex("EspecieId", "Numero")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("UnidadesFaenas");
                });

            modelBuilder.Entity("Meat.Domain.UnidadesMedidas.UnidadMedida", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("UnidadesMedidas");
                });

            modelBuilder.Entity("Meat.Domain.UsosHaciendas.UsoHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("UsosHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosEstablecimientos.UsuarioEstablecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("UsuarioId", "EstablecimientoId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("UsuariosEstablecimientos");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosSucursales.UsuarioSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "SucursalId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("UsuariosSucursales");
                });

            modelBuilder.Entity("Meat.Domain.Almacenes.Almacen", b =>
                {
                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposAlmacenes.TipoAlmacen", "TipoAlmacen")
                        .WithMany()
                        .HasForeignKey("TipoAlmacenId");

                    b.Navigation("Establecimiento");

                    b.Navigation("TipoAlmacen");
                });

            modelBuilder.Entity("Meat.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Meat.Domain.TiposClientes.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Meat.Domain.Denticiones.Denticion", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.TiposDenticiones.TipoDenticion", "TipoDenticion")
                        .WithMany()
                        .HasForeignKey("TipoDenticionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");

                    b.Navigation("TipoDenticion");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.HasOne("Meat.Domain.TiposEmpresas.TipoEmpresa", "TipoEmpresa")
                        .WithMany()
                        .HasForeignKey("TipoEmpresaId");

                    b.Navigation("TipoEmpresa");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany("Establecimientos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Sucursales.Sucursal", "Sucursal")
                        .WithMany("Establecimientos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Meat.Domain.EstablecimientosEspecies.EstablecimientoEspecie", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId");

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany("Especies")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.HasOne("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", "ClienteEstablecimiento")
                        .WithMany()
                        .HasForeignKey("ClienteEstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEstadosIngresos.TipoEstadoIngreso", "EstadoIngreso")
                        .WithMany()
                        .HasForeignKey("EstadoIngresoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.OrigenesHaciendas.OrigenHacienda", "OrigenHacienda")
                        .WithMany()
                        .HasForeignKey("OrigenHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Provincias.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.UsosHaciendas.UsoHacienda", "UsoHacienda")
                        .WithMany()
                        .HasForeignKey("UsoHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("ClienteEstablecimiento");

                    b.Navigation("Especie");

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoIngreso");

                    b.Navigation("OrigenHacienda");

                    b.Navigation("Provincia");

                    b.Navigation("UsoHacienda");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaPesada", b =>
                {
                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Pesadas")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IngresoHacienda");

                    b.Navigation("TipoEspecie");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaUbicacion", b =>
                {
                    b.HasOne("Meat.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEstadosHacienda.TipoEstadoHacienda", "EstadoHacienda")
                        .WithMany()
                        .HasForeignKey("EstadoHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Tropas.Tropa", "Tropa")
                        .WithMany()
                        .HasForeignKey("TropaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Almacen");

                    b.Navigation("EstadoHacienda");

                    b.Navigation("IngresoHacienda");

                    b.Navigation("TipoEspecie");

                    b.Navigation("Tropa");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanza", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEstadosListasMatanzas.TipoEstadoListaMatanza", "EstadoListaMatanza")
                        .WithMany()
                        .HasForeignKey("EstadoListaMatanzaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Puestos.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoListaMatanza");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanzaDetalle", b =>
                {
                    b.HasOne("Meat.Domain.Almacenes.Almacen", "AlmacenDestino")
                        .WithMany()
                        .HasForeignKey("AlmacenDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.ListasMatanzas.ListaMatanza", "ListaMatanza")
                        .WithMany("Renglones")
                        .HasForeignKey("ListaMatanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Tropas.Tropa", "Tropa")
                        .WithMany()
                        .HasForeignKey("TropaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("AlmacenDestino");

                    b.Navigation("ListaMatanza");

                    b.Navigation("TipoEspecie");

                    b.Navigation("Tropa");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanzaMovimiento", b =>
                {
                    b.HasOne("Meat.Domain.ListasMatanzas.ListaMatanza", "ListaMatanza")
                        .WithMany("Movimientos")
                        .HasForeignKey("ListaMatanzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaMatanza");
                });

            modelBuilder.Entity("Meat.Domain.Materiales.Material", b =>
                {
                    b.HasOne("Meat.Domain.TiposMateriales.TipoMaterial", "TipoMaterial")
                        .WithMany()
                        .HasForeignKey("TipoMaterialId");

                    b.HasOne("Meat.Domain.UnidadesMedidas.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId");

                    b.Navigation("TipoMaterial");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Meat.Domain.MotivosDecomisos.MotivoDecomiso", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.Numeradores.Numerador", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieCodigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Meat.Domain.NumeradoresTropas.NumeradorTropa", b =>
                {
                    b.HasOne("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", "ClienteEstablecimiento")
                        .WithMany()
                        .HasForeignKey("ClienteEstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieCodigo");

                    b.Navigation("ClienteEstablecimiento");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.Parametros.Parametro", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Meat.Domain.Puestos.Puesto", b =>
                {
                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposPuestos.TipoPuesto", "TipoPuesto")
                        .WithMany()
                        .HasForeignKey("TipoPuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Establecimiento");

                    b.Navigation("TipoPuesto");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Meat.Domain.Tipificaciones.Tipificacion", b =>
                {
                    b.HasOne("Meat.Domain.DestinosComerciales.DestinoComercial", "DestinoComercial")
                        .WithMany()
                        .HasForeignKey("DestinoComercialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.TipificacionesOficiales.TipificacionOficial", "TipificacionOficial")
                        .WithMany()
                        .HasForeignKey("TipificacionOficialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.UnidadesFaenas.UnidadFaena", "UnidadFaena")
                        .WithMany()
                        .HasForeignKey("UnidadFaenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.UnidadesMedidas.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinoComercial");

                    b.Navigation("Especie");

                    b.Navigation("TipificacionOficial");

                    b.Navigation("TipoEspecie");

                    b.Navigation("UnidadFaena");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Meat.Domain.TipificacionesOficiales.TipificacionOficial", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.TiposContusiones.TipoContusion", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.TiposDenticiones.TipoDenticion", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.TiposEspecies.TipoEspecie", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId");

                    b.HasOne("Meat.Domain.TiposSexos.TipoSexo", "TipoSexo")
                        .WithMany()
                        .HasForeignKey("TipoSexoId");

                    b.Navigation("Especie");

                    b.Navigation("TipoSexo");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.Tropa", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieCodigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.TiposEstadosTropas.TipoEstadoTropa", "EstadoTropa")
                        .WithMany()
                        .HasForeignKey("EstadoTropaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Tropas")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("EstadoTropa");

                    b.Navigation("IngresoHacienda");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.TropaMovimiento", b =>
                {
                    b.HasOne("Meat.Domain.TiposEstadosTropas.TipoEstadoTropa", "EstadoResultante")
                        .WithMany()
                        .HasForeignKey("EstadoResultanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Tropas.Tropa", "Tropa")
                        .WithMany()
                        .HasForeignKey("TropaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoResultante");

                    b.Navigation("Tropa");
                });

            modelBuilder.Entity("Meat.Domain.UnidadesFaenas.UnidadFaena", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.UnidadesFaenas.UnidadFaena", "UnidadComplementaria")
                        .WithMany()
                        .HasForeignKey("UnidadComplementariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especie");

                    b.Navigation("UnidadComplementaria");
                });

            modelBuilder.Entity("Meat.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Meat.Domain.Roles.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosEstablecimientos.UsuarioEstablecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosSucursales.UsuarioSucursal", b =>
                {
                    b.HasOne("Meat.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.Navigation("Establecimientos");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.Navigation("Pesadas");

                    b.Navigation("Tropas");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Meat.Domain.ListasMatanzas.ListaMatanza", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Renglones");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.Navigation("Establecimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
