// <auto-generated />
using System;
using Meat.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meat.Repositories.Migrations
{
    [DbContext(typeof(MeatContext))]
    [Migration("20260630145446_30_IngresoHacienda")]
    partial class _30_IngresoHacienda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meat.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadAnimales")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAlmacen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAlmacenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("TipoAlmacenId");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("Meat.Domain.AlmacenesMateriales.AlmacenMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoAnimalId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TipoAnimalId");

                    b.ToTable("AlmacenesMateriales");
                });

            modelBuilder.Entity("Meat.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIngresosBrutos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCliente")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoRenspa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCUIG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("ClienteId", "EstablecimientoId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("ClientesEstablecimientos");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIngresosBrutos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroInscripcionRuca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpresaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoEmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Meat.Domain.Especies.Especie", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoEstablecimiento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRuca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSenasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEstablecimiento")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("Meat.Domain.EstablecimientosEspecies.EstablecimientoEspecie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("EstablecimientoId", "EspecieId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("EstablecimientosEspecies");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoIngresoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmisionDte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroIngreso")
                        .HasColumnType("bigint");

                    b.Property<string>("OrigenHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatenteCamion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteJaula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoBruto")
                        .HasColumnType("float");

                    b.Property<double>("PesoNeto")
                        .HasColumnType("float");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<double>("Tara")
                        .HasColumnType("float");

                    b.Property<string>("Transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsoHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UsuarioAprobacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEstablecimientoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoIngresoId");

                    b.HasIndex("OrigenHaciendaId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("UsoHaciendaId");

                    b.HasIndex("EstablecimientoId", "NumeroIngreso")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("IngresosHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaPesada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PesoIngreso")
                        .HasColumnType("float");

                    b.Property<string>("TipoEspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("TipoEspecieId");

                    b.ToTable("IngresosHaciendasPesadas");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaUbicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoHaciendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PesoPromedio")
                        .HasColumnType("float");

                    b.Property<string>("TipoEspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TropaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("EstadoHaciendaId");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("TipoEspecieId");

                    b.HasIndex("TropaId");

                    b.ToTable("IngresosHaciendasUbicaciones");
                });

            modelBuilder.Entity("Meat.Domain.Materiales.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoTeorico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMaterialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnidadMedidaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaterialId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Meat.Domain.NumeradoresTropas.NumeradorTropa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<long>("UltimoNumeroTropa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("ClienteEstablecimientoId", "EspecieCodigo")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("NumeradoresTropas");
                });

            modelBuilder.Entity("Meat.Domain.OrigenesHaciendas.OrigenHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("OrigenesHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.Parametros.Parametro", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Meat.Domain.Provincias.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Meat.Domain.Puestos.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erp_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("Meat.Domain.Roles.Rol", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoSucursal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Erp_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Meat.Domain.TiposAlmacenes.TipoAlmacen", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposAlmacenes");
                });

            modelBuilder.Entity("Meat.Domain.TiposAnimales.TipoAnimal", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposAnimales");
                });

            modelBuilder.Entity("Meat.Domain.TiposClientes.TipoCliente", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposClientes");
                });

            modelBuilder.Entity("Meat.Domain.TiposEmpresas.TipoEmpresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEmpresas");
                });

            modelBuilder.Entity("Meat.Domain.TiposEspecies.TipoEspecie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoTeorico")
                        .HasColumnType("float");

                    b.Property<string>("TipoSexoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("TipoSexoId");

                    b.ToTable("TiposEspecies");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosHacienda.TipoEstadoHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosHacienda");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosIngresos.TipoEstadoIngreso", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosIngresos");
                });

            modelBuilder.Entity("Meat.Domain.TiposEstadosTropas.TipoEstadoTropa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposEstadosTropas");
                });

            modelBuilder.Entity("Meat.Domain.TiposMateriales.TipoMaterial", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMateriales");
                });

            modelBuilder.Entity("Meat.Domain.TiposSexos.TipoSexo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TiposSexos");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.Tropa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteEstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EspecieCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoTropaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngresoHaciendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NumeroTropa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("EstadoTropaId");

                    b.HasIndex("IngresoHaciendaId");

                    b.HasIndex("ClienteEstablecimientoId", "EspecieCodigo", "NumeroTropa")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("Tropas");
                });

            modelBuilder.Entity("Meat.Domain.UnidadesMedidas.UnidadMedida", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("UnidadesMedidas");
                });

            modelBuilder.Entity("Meat.Domain.UsosHaciendas.UsoHacienda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("UsosHaciendas");
                });

            modelBuilder.Entity("Meat.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosEstablecimientos.UsuarioEstablecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("UsuarioId", "EstablecimientoId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("UsuariosEstablecimientos");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosSucursales.UsuarioSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "SucursalId")
                        .IsUnique()
                        .HasFilter("[FechaBaja] IS NULL");

                    b.ToTable("UsuariosSucursales");
                });

            modelBuilder.Entity("Meat.Domain.Almacenes.Almacen", b =>
                {
                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposAlmacenes.TipoAlmacen", "TipoAlmacen")
                        .WithMany()
                        .HasForeignKey("TipoAlmacenId");

                    b.Navigation("Establecimiento");

                    b.Navigation("TipoAlmacen");
                });

            modelBuilder.Entity("Meat.Domain.AlmacenesMateriales.AlmacenMaterial", b =>
                {
                    b.HasOne("Meat.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Materiales.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposAnimales.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("TipoAnimalId");

                    b.Navigation("Almacen");

                    b.Navigation("Material");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("Meat.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Meat.Domain.TiposClientes.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.HasOne("Meat.Domain.TiposEmpresas.TipoEmpresa", "TipoEmpresa")
                        .WithMany()
                        .HasForeignKey("TipoEmpresaId");

                    b.Navigation("TipoEmpresa");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany("Establecimientos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Sucursales.Sucursal", "Sucursal")
                        .WithMany("Establecimientos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Meat.Domain.EstablecimientosEspecies.EstablecimientoEspecie", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId");

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany("Especies")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.HasOne("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", "ClienteEstablecimiento")
                        .WithMany()
                        .HasForeignKey("ClienteEstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEstadosIngresos.TipoEstadoIngreso", "EstadoIngreso")
                        .WithMany()
                        .HasForeignKey("EstadoIngresoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.OrigenesHaciendas.OrigenHacienda", "OrigenHacienda")
                        .WithMany()
                        .HasForeignKey("OrigenHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Provincias.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.UsosHaciendas.UsoHacienda", "UsoHacienda")
                        .WithMany()
                        .HasForeignKey("UsoHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("ClienteEstablecimiento");

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoIngreso");

                    b.Navigation("OrigenHacienda");

                    b.Navigation("Provincia");

                    b.Navigation("UsoHacienda");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaPesada", b =>
                {
                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Pesadas")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IngresoHacienda");

                    b.Navigation("TipoEspecie");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHaciendaUbicacion", b =>
                {
                    b.HasOne("Meat.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEstadosHacienda.TipoEstadoHacienda", "EstadoHacienda")
                        .WithMany()
                        .HasForeignKey("EstadoHaciendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.TiposEspecies.TipoEspecie", "TipoEspecie")
                        .WithMany()
                        .HasForeignKey("TipoEspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.Tropas.Tropa", "Tropa")
                        .WithMany()
                        .HasForeignKey("TropaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Almacen");

                    b.Navigation("EstadoHacienda");

                    b.Navigation("IngresoHacienda");

                    b.Navigation("TipoEspecie");

                    b.Navigation("Tropa");
                });

            modelBuilder.Entity("Meat.Domain.Materiales.Material", b =>
                {
                    b.HasOne("Meat.Domain.TiposMateriales.TipoMaterial", "TipoMaterial")
                        .WithMany()
                        .HasForeignKey("TipoMaterialId");

                    b.HasOne("Meat.Domain.UnidadesMedidas.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId");

                    b.Navigation("TipoMaterial");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Meat.Domain.NumeradoresTropas.NumeradorTropa", b =>
                {
                    b.HasOne("Meat.Domain.ClientesEstablecimientos.ClienteEstablecimiento", "ClienteEstablecimiento")
                        .WithMany()
                        .HasForeignKey("ClienteEstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieCodigo");

                    b.Navigation("ClienteEstablecimiento");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Meat.Domain.Parametros.Parametro", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Meat.Domain.Puestos.Puesto", b =>
                {
                    b.HasOne("Meat.Domain.Sucursales.Sucursal", "Sucursal")
                        .WithMany("Puestos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.HasOne("Meat.Domain.Empresas.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Meat.Domain.TiposEspecies.TipoEspecie", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId");

                    b.HasOne("Meat.Domain.TiposSexos.TipoSexo", "TipoSexo")
                        .WithMany()
                        .HasForeignKey("TipoSexoId");

                    b.Navigation("Especie");

                    b.Navigation("TipoSexo");
                });

            modelBuilder.Entity("Meat.Domain.Tropas.Tropa", b =>
                {
                    b.HasOne("Meat.Domain.Especies.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieCodigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.TiposEstadosTropas.TipoEstadoTropa", "EstadoTropa")
                        .WithMany()
                        .HasForeignKey("EstadoTropaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meat.Domain.IngresosHaciendas.IngresoHacienda", "IngresoHacienda")
                        .WithMany("Tropas")
                        .HasForeignKey("IngresoHaciendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("EstadoTropa");

                    b.Navigation("IngresoHacienda");
                });

            modelBuilder.Entity("Meat.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Meat.Domain.Roles.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosEstablecimientos.UsuarioEstablecimiento", b =>
                {
                    b.HasOne("Meat.Domain.Establecimientos.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meat.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meat.Domain.UsuariosSucursales.UsuarioSucursal", b =>
                {
                    b.HasOne("Meat.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meat.Domain.Empresas.Empresa", b =>
                {
                    b.Navigation("Establecimientos");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Meat.Domain.Establecimientos.Establecimiento", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("Meat.Domain.IngresosHaciendas.IngresoHacienda", b =>
                {
                    b.Navigation("Pesadas");

                    b.Navigation("Tropas");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Meat.Domain.Sucursales.Sucursal", b =>
                {
                    b.Navigation("Establecimientos");

                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
